### ISSUE TITLE
Ajouter la liste des tags sur la page web

### ISSUE THREAD

**Issue by alexandre-janniaux** [friendshipismagic/Hecateros#1]
Actuellement, on peut récupérer les liens associés à un certain tag en cliquant sur le tag, mais il n'y a pas de possibilité ergonomique d'aller chercher un tag particulier autre qu'en cherchant un lien avec ce tag, et surtout pas de possibilité de savoir quels tags existent.

**Comment by tchoutri** [comment]
J'ajoute ça dans la TODO :)

**Comment by tchoutri** [comment]
Est-ce que ce prototype te conviens @alexandre-janniaux ?

![screenshot-2017-12-5 hecateros](https://user-images.githubusercontent.com/15848443/33581259-81529966-d950-11e7-969f-e6c6b8dcbb51.png)

**Comment by alexandre-janniaux** [comment]
Comme ceci, pour garder la superbe sobriété de l'interface ? 

![Image hecateros](https://zestedesavoir.com/media/galleries/1491/9453744c-939d-4e17-be33-da224deb19d9.png)

**Comment by tchoutri** [comment]
Du coup il va falloir scroller à mort pour trouver les tags si y'a ~100 liens pour un chan (ça peut aller très vite), ou bien faire de la pagination en fonction de la taille de l'écran de l'utilisateur, ce qui sans JS va être un peu cho. Voir même cho patate.
Enfin, je vois que ça comme façon de le faire, si tu as une idée de comment je suis preneur (pour y réfléchir). :)

**Comment by alexandre-janniaux** [comment]
séparer l'écran en deux divs scrollables, ou mettre les tags sur une autre page ?

**Comment by tchoutri** [comment]
>deux divs scrollabes
Genre… des frames… ? 😮 
Mettre les tags sur une autre page ça va être méga-relou en terme d'utilisation. Peut-être les coller en haut du coup ?

**Comment by alexandre-janniaux** [comment]
Tu peux faire un div qui prend une taille d'écran fixé (genre 1/5 du bas) et qui est fixé en bas, scrollable. Mais effectivement c'est pas génial, j'étais plus fan de l'autre page.

Il faudra peut etre les mettre comme tu as mis à droite sinon, mais tu perdras le côté sobre de la page. :(

**Comment by tchoutri** [comment]
On laisse la discussion en suspend. :) Je ferme pour l'instant
