### ISSUE TITLE
Hecateros ne gère pas les 302 correctement

### ISSUE THREAD

**Issue by alexandre-janniaux** [friendshipismagic/Hecateros#4]
Si on entre une url qui redirige sur un 302, hecateros enregistre l'url donnée et non le site redirigé. Cela va poser problème avec les redirections http -> https.

Exemple : http://hecateros.kratom.random.sh/c/d8cd340e

**Comment by tchoutri** [comment]
fixé dans 59cc62f2d0d75a21a686a8e349a2a111e5c2389a
